config/routes.rb
ProductsCategoriesApp::Application.routes.draw do
 
  resources :sites, :products, :categories

  root to: 'sites#index'

  # get '/go/all_products', to: 'products#display_products'


end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :inventories
	has_many :products, through: :inventories
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :inventories
	has_many :categories, through: :inventories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

 	def index
        @categories = Category.all
	end

	def new
	    @category = Category.new
	end

	def show
        id = params.require(:id)
        @category = Category.find(id)
        @products = @category.products
	end

	def create
        parameters = params.require(:category).permit(:name)
        category = Category.create(parameters)
        redirect_to category
	end

	def edit
        id = params[:id]
        @category = Category.find(id)
	end

	def update
        id = params[:id]
        change = params.require(:category).permit(:name)
        category = Category.find(id)
        category.update(change)
        redirect_to category
	end

	def destroy
        id = params[:id]
        Category.destroy(id)
        redirect_to :categories
	end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
        @products = Product.all
    end

    def new
        @product = Product.new
    end

    def show
        id = params.require(:id)
        @product = Product.find(id)
        @categories = @product.categories
    end

    def create
        parameters = params.require(:product).permit(:name, :description)
        product = Product.create(parameters)
        redirect_to product
    end

    def edit
        id = params[:id]
        @product = Product.find(id)
    end

	def update
		id = params[:id]
		change = params.require(:product).permit(:name, :price, :description)
		product = Product.find(id)
		product.update(change)
		redirect_to product
	end

	def destroy
		id = params[:id]
		Product.destroy(id)
		redirect_to :products
	end

	def display_products
		@products = Product.all
	end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

	def new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for @category do |f| %>
	<%= f.label 'Name' %>
	<%= f.text_field :name, placeholder: 'Name' %><br>
	<%= f.submit %>
<% end %>

app/views/categories/index.html.erb
<h3>Categories</h3>

<%= link_to "Create a new Category", new_category_path %><br>

<% @categories.each do |c| %>
	<% link_to c.name, category_path(c) %>
<% end %>

app/views/categories/new.html.erb
<h4>Create New Category</h4>

<%= form_for @category do |f| %>
	<%= f.text_field :name, placeholder: 'Name' %><br>
	<%= f.submit %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<%= link_to "Edit", edit_category_path(@category), method: 'get' %> 
<%= link_to "Delete", category_path(@category), method: 'delete' %>

<h3>Products:</h3>

<% @products.each do |p| %>
	<li><%= link_to p.name, product_path(p) %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductsCategoriesApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/display_products.html.erb
<h2>List of Available Products</h2>

<table>
	<tr>
		<td>Name</td>
		<td>Price</td>
		<td>Description</td>
		<td>Categories</td>
	</tr>
	<%= @products.each do |p| %>
	<tr>
		<td><%= p.name %></td>
		<td><%= p.price %></td>
		<td><%= p.description %></td>
		<td><%= p.categories %></td>
	</tr>
	<% end %>
</table>

app/views/products/edit.html.erb
<h2>Edit Product</h2>

<%= form_for @product do |f| %>
	<%= f.text_field :name, placeholder: 'Name' %><br>
	<%= f.text_field :price, placeholder: 'Price' %><br>
	<%= f.text_area :description, placeholder: 'Description' %><br>
	<%= f.submit %>
<% end %>

app/views/products/index.html.erb
<h3>Products</h3>

<%= link_to "Create a new Product", new_product_path %><br>

<% @products.each do |p| %>
	<% link_to p.name, product_path(p) %>
<% end %>

app/views/products/new.html.erb
<h4>Please Enter the Products Information</h4>

<%= form_for @product do |f| %>
	<%= f.text_field :name, placeholder: 'Name' %><br>
	<%= f.text_field :price, placeholder: 'Price' %><br>
	<%= f.text_area :description, placeholder: 'Description' %><br>

	<h5>Select Categories:</h5>

	<%= f.submit %>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p><%= @product.price %></p>
<p><%= @product.description %></p>
<%= link_to "Edit", edit_product_path(@product), method: 'get' %> 
<%= link_to "Delete", product_path(@product), method: 'delete' %>

<h3>Categories:</h3>

<% @categories.each do |c| %>
	<li><%= link_to c.name, category_path(c) %></li>
<% end %>

app/views/sites/index.html.erb
<h3>Welcome</h3>

<%= link_to "Products", products_path %><br>
<%= link_to "Categories", categories_path %>